Our team
bellshade/bellshade-website-v2 pull request #14
Opened 2022-03-04 17:14 UTC by dhafitf

## Deskripsi
Membuat dan menambahkan bagian our-team pada halaman home.

Saya menggunakan sistem operasi:

- `os` = `windows`

2022-03-06 12:26 UTC, reacto11mecha requested changes
Di cek di local sesuai sama designya, text nya truncated jadi ga overfow kemana mana, mantap om :+1: Sisanya tinggal masalah penulisan kode sama aku mau nanya sesuatu

2022-03-06 12:26 UTC, reacto11mecha commented on components/pages/home/MemberCard.js
> +    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAPtJREFUeF7t0rENAAAMwrDy/9M9wmvYs1jsGgmM6uILEE8QYIAogHkPDBAFMO+BAaIA5j0wQBTAvAcGiAKY98AAUQDzHhggCmDeAwNEAcx7
Dihapus aja om, soalnya mah avatar di setiap user pasti ada di setiap usernya, pasti ada url foto profilnya, nanti kan udah di urusin gambar dummynya pas belum ke load sama next js nya

```suggestion
```

2022-03-06 12:26 UTC, reacto11mecha commented on components/pages/home/MemberCard.js
> +            src={avatar_url ? `${avatar_url}&s=80` : dummyImage}
Lanjutan dari yang review di atas, url avatarnya aja yang dimasukin

```suggestion
            src={`${avatar_url}&s=80`}
```

Tapi sebenernya kalo `next/image` udah ngeresize kan ?

2022-03-06 12:26 UTC, reacto11mecha commented on pages/index.js
> +}
Mau nanya om, ini sebenernya bisa ga sih kalo datanya pake `getStaticProps` ? Soalnya ngabisin bandwith juga kalo datanya jarang update, soalnya data yang ada di server di update tiap 5 hari sekali, terus di update pake isr nya next ?

File konfigurasi updatenya ada di file ini
https://github.com/bellshade/bellshade-server/blob/c9dc92453a2e12353f60b22b769edef0e1dff143/config/constant.js#L24-L32

https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

2022-03-06 12:26 UTC, reacto11mecha commented on pages/index.js
> +}
Atau mungkin perlu ku update di deskripsi web dokumentasi api nya ?

2022-03-06 13:35 UTC, dhafitf commented on components/pages/home/MemberCard.js
> +            src={avatar_url ? `${avatar_url}&s=80` : dummyImage}
Saya pakai `layout="fill"`, jadi ukurannya ngikutin ukuran parrentnya.

2022-03-06 13:39 UTC, dhafitf commented on pages/index.js
> +}
Kalau mau pake isr bisa sih, mau ngikutin api bellshade yang update setiap 5 hari aja? Nanti set `revalidate: 432000`

2022-03-06 13:40 UTC, dhafitf commented on pages/index.js
> +}
> Atau mungkin perlu ku update di deskripsi web dokumentasi api nya ?

Boleh, sekalian di update aja deskripsinya.

2022-03-06 14:07 UTC, reacto11mecha commented on pages/index.js
> +}
> Kalau mau pake isr bisa sih, mau ngikutin api bellshade yang update setiap 5 hari aja? Nanti set `revalidate: 432000`

Iya om, diubah jadi static prop sama pakein isr 5 hari

2022-03-06 23:13 UTC, reacto11mecha requested changes
Oiya om kelupaan, bikin componentnya di luar index, nanti dia berantakan kalo di taro semua di index. Terus juga diubah nama file `MemberCard.js` sama `MemberCard.stories.js` jadi `OurTeam.js` sama `OurTeam.stories.js`

2022-03-06 23:13 UTC, reacto11mecha commented on components/pages/home/MemberCard.js
> +const MemberCard = ({ login, name, html_url, avatar_url }) => {
Di export aja om tetep tapi jangan jadiin default

```suggestion
export const MemberCard = ({ login, name, html_url, avatar_url }) => {
```

2022-03-06 23:13 UTC, reacto11mecha commented on pages/index.js
> +import MemberCard from "@/components/pages/home/MemberCard";
Diubah path importnya

```suggestion
import OurTeam from "@/components/pages/home/OurTean";
```

2022-03-06 23:13 UTC, reacto11mecha commented on pages/index.js
> +      </section>
Yang ini nanti di pindahin ke component our teamnya

```suggestion
      <OurTeam members={members} />
```

2022-03-06 23:13 UTC, reacto11mecha commented on components/pages/home/MemberCard.js
> +export default MemberCard;
Yang ada di index pindahin kesini

```suggestion

const OurTeam = ({ members }) => {
    return (
        <section
        id="team"
        className="max-w-[942px] m-auto"
        style={{ width: "90%" }}
      >
        <div className="w-full mb-16 md:mb-20 text-center">
          <h2 className="text-5xl md:text-[67px] font-bold">Meet Our Team</h2>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5">
          {members.map((member) => {
            return <MemberCard key={member.login} {...member} />;
          })}
        </div>
      </section>
    )
}

export default OurTeam;
```

2022-03-08 08:14 UTC, dhafitf commented on components/pages/home/MemberCard.js
> +const MemberCard = ({ login, name, html_url, avatar_url }) => {
Yang di storybook sama ya, biar lebih enak buat coba coba. 

![image](https://user-images.githubusercontent.com/87353624/157194667-99e3c7dc-3876-441c-b59c-a42d11137829.png)

2022-03-08 08:29 UTC, reacto11mecha commented on components/pages/home/MemberCard.js
> +const MemberCard = ({ login, name, html_url, avatar_url }) => {
Iya om samain aja gapapa

2022-03-08 12:54 UTC, reacto11mecha approved these changes
Sip om, lebih kenceng pake isr kebanding ssr, LGTM :+1:

2022-03-11 08:29 UTC, merged