Optimize next compiler for local development and make next js script production ready
bellshade/bellshade-website-v2 pull request #8
Opened 2022-02-13 13:26 UTC by rahmatagungj

## **Problem Description**
As a developer i need to increase productivity and development speed, also if looking as a user i need to load script more faster. 

### **What problem are you trying to solve?**

### **How ​​this problem is currently solved**
- Creating custom defered next js script
- Add more configuration for local development

### **Why is this important to solve?**
- Make developer more than happier
- User can access bellshade web faster

## **Technical Aspects That Need Attention**
- Some configuration need to adjust with our timeline

## **QA**

N/A

## **Other Decisions**

N/A

2022-02-13 14:36 UTC, reacto11mecha requested changes

2022-02-13 14:36 UTC, reacto11mecha commented on pages/_document.js
> +          <meta name="twitter:card" content="summary_large_image" />
Oiya kelupaan, untuk yang preconnect gapapa, dipakein aja

2022-02-13 14:43 UTC, rahmatagungj commented on pages/_document.js
> +          <meta name="twitter:card" content="summary_large_image" />
refactored @reacto11mecha with branch fix/identity-refactor

2022-02-13 14:44 UTC, reacto11mecha approved these changes
Sip LGTM :+1:  Terimakasih atas kontribusinya

2022-02-14 01:31 UTC, hasheemi approved these changes

2022-02-14 04:23 UTC, nomadkode approved these changes

2022-02-14 05:38 UTC, dhafitf approved these changes

2022-02-14 11:30 UTC, dipras approved these changes
LGTM
Meluncur Deploy :rocket:

2022-02-14 11:31 UTC, merged